BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Brochure] ALTER COLUMN [pdfFileUrl] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Brochure] ADD [comingSoon] BIT NOT NULL CONSTRAINT [Brochure_comingSoon_df] DEFAULT 1;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
